language: rust
rust:
  - nightly
before_script:
  - rustup component add rustfmt
script:
  - cargo fmt --all -- --check
  - cargo build --bin mksfs --features "std"
  - cargo test --verbose -- --test-threads=1